import React, { useState, useEffect, useRef, useCallback } from "react";
import "./AudioPlayer.css";
import { BsMusicNoteBeamed } from "react-icons/bs";
import apiClient from "../../api/apiClient";

const AudioPlayer = ({ title, fileId, lessonId }) => {
  const [audioUrl, setAudioUrl] = useState(null);
  const [status, setStatus] = useState("idle"); // idle | preparing | ready | error
  const [error, setError] = useState("");
  const pollRef = useRef(null);
  const mountedRef = useRef(true);

  // ── Call /audio/prepare and handle response ──────────────────
  const callPrepare = useCallback(async () => {
    if (!lessonId) return null;
    try {
      const { data } = await apiClient.post("/ai-generations/audio/prepare", {
        lesson_id: lessonId,
        language: "ar",
      });

      if (data.status === "ready" && data.audio_url) {
        return data.audio_url;
      }
      // status === "processing" or other — not ready yet
      return null;
    } catch (err) {
      console.error("[AudioPlayer] prepare failed:", err.message);
      return null;
    }
  }, [lessonId]);

  // ── Poll until audio is ready ────────────────────────────────
  const loadAudio = useCallback(async () => {
    if (!lessonId || !fileId) return;
    setStatus("preparing");
    setError("");
    setAudioUrl(null);

    // Poll up to 120 times (10 minutes at 5s intervals)
    for (let i = 0; i < 120; i++) {
      if (!mountedRef.current) return;

      const url = await callPrepare();
      if (url) {
        if (mountedRef.current) {
          setAudioUrl(url);
          setStatus("ready");
        }
        return;
      }

      // Wait 5 seconds before retrying
      await new Promise((resolve) => {
        pollRef.current = setTimeout(resolve, 5000);
      });
    }

    // Exhausted retries
    if (mountedRef.current) {
      setStatus("error");
      setError("Audio is still processing. Please try again later.");
    }
  }, [lessonId, fileId, callPrepare]);

  // ── Start loading when component mounts with a fileId ────────
  useEffect(() => {
    mountedRef.current = true;

    if (fileId && lessonId) {
      loadAudio();
    }

    return () => {
      mountedRef.current = false;
      if (pollRef.current) clearTimeout(pollRef.current);
    };
  }, [fileId, lessonId, loadAudio]);

  // ── Preparing state ────────────────────────────────────────────
  if (status === "preparing") {
    return (
      <div className="audio-player-container">
        <div className="icon-wrapper">
          <BsMusicNoteBeamed className="music-icon" style={{ animation: 'spin 2s linear infinite' }} />
        </div>
        <h3 className="track-title">{title || "AI Audio Lesson"}</h3>
        <p className="track-subtitle">Preparing your audio… this may take a few minutes.</p>
      </div>
    );
  }

  // ── Error state ────────────────────────────────────────────────
  if (status === "error") {
    return (
      <div className="audio-player-container">
        <div className="icon-wrapper">
          <BsMusicNoteBeamed className="music-icon" />
        </div>
        <h3 className="track-title">{title || "AI Audio Lesson"}</h3>
        <p className="track-subtitle">{error}</p>
        <button
          onClick={loadAudio}
          style={{
            marginTop: '0.75rem',
            padding: '0.45rem 1.2rem',
            borderRadius: '8px',
            border: '1px solid rgba(255,255,255,0.15)',
            background: 'rgba(255,255,255,0.08)',
            color: '#fff',
            cursor: 'pointer',
            fontSize: '0.85rem',
          }}
        >
          🔄 Try Again
        </button>
      </div>
    );
  }

  // ── Ready — play audio directly from S3 pre-signed URL ─────────
  if (status === "ready" && audioUrl) {
    return (
      <div className="audio-player-real">
        <div className="audio-player-real__icon">
          <BsMusicNoteBeamed size={32} />
        </div>
        <div className="audio-player-real__info">
          <p className="audio-player-real__title">{title || "AI Audio Lesson"}</p>
          <p className="audio-player-real__sub">AI Voice Lesson</p>
        </div>
        <audio
          key={audioUrl}
          controls
          className="audio-player-real__element"
          src={audioUrl}
          preload="metadata"
        >
          Your browser does not support the audio element.
        </audio>
      </div>
    );
  }

  // ── Idle placeholder (no audio record yet) ─────────────────────
  const waveformBars = [20,40,30,50,40,60,30,50,40,30,20,40,50,60,70,50,40,60,50,40,30,20,40,30,50,40,60,30,50,40];

  return (
    <div className="audio-player-container">
      <div className="icon-wrapper">
        <BsMusicNoteBeamed className="music-icon" />
      </div>
      <h3 className="track-title">{title || "AI Audio Lesson"}</h3>
      <p className="track-subtitle">Audio will appear here once generated by AI</p>

      <div className="waveform waveform--inactive">
        {waveformBars.map((height, index) => (
          <div key={index} className="wave-bar" style={{ height: `${height}%` }} />
        ))}
      </div>
    </div>
  );
};

export default AudioPlayer;