import React from "react";
import "./AudioPlayer.css";
import { BsMusicNoteBeamed } from "react-icons/bs";

// Extract Drive file ID from stored URL formats
function getDriveFileId(url) {
  if (!url) return null;
  try {
    const idParam = new URL(url).searchParams.get("id");
    if (idParam) return idParam;
    const match = url.match(/\/d\/([a-zA-Z0-9_-]+)/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

const AudioPlayer = ({ title, filePath, fileId }) => {
  const driveId = getDriveFileId(filePath);

  // ── Real audio player ──────────────────────────────────────────
  if (driveId || fileId) {
    // Use backend stream proxy for reliable auth + CORS handling
    const streamSrc = fileId
      ? `/api/lesson-files/stream/${fileId}`
      : `https://drive.google.com/uc?export=download&id=${driveId}`;

    return (
      <div className="audio-player-real">
        <div className="audio-player-real__icon">
          <BsMusicNoteBeamed size={32} />
        </div>
        <div className="audio-player-real__info">
          <p className="audio-player-real__title">{title || "AI Audio Lesson"}</p>
          <p className="audio-player-real__sub">AI Voice Lesson</p>
        </div>
        <audio
          controls
          className="audio-player-real__element"
          src={streamSrc}
          preload="metadata"
        >
          Your browser does not support the audio element.
        </audio>
      </div>
    );
  }

  // ── Placeholder (audio not yet generated) ─────────────────────
  const waveformBars = [20,40,30,50,40,60,30,50,40,30,20,40,50,60,70,50,40,60,50,40,30,20,40,30,50,40,60,30,50,40];

  return (
    <div className="audio-player-container">
      <div className="icon-wrapper">
        <BsMusicNoteBeamed className="music-icon" />
      </div>
      <h3 className="track-title">{title || "AI Audio Lesson"}</h3>
      <p className="track-subtitle">Audio will appear here once generated by AI</p>

      <div className="waveform waveform--inactive">
        {waveformBars.map((height, index) => (
          <div key={index} className="wave-bar" style={{ height: `${height}%` }} />
        ))}
      </div>
    </div>
  );
};

export default AudioPlayer;