import React from "react";
import "./VideoPlayer.css";

// Extract Drive file ID from stored URL formats
function getDriveFileId(url) {
  if (!url) return null;
  try {
    const idParam = new URL(url).searchParams.get("id");
    if (idParam) return idParam;
    const match = url.match(/\/d\/([a-zA-Z0-9_-]+)/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

function VideoPlayer({ title, filePath }) {
  const driveId = getDriveFileId(filePath);

  if (driveId) {
    // Real video via Google Drive's built-in iframe player
    return (
      <div className="video-embed-wrapper">
        <iframe
          src={`https://drive.google.com/file/d/${driveId}/preview`}
          title={title}
          allow="autoplay; fullscreen"
          allowFullScreen
          className="video-embed-iframe"
        />
      </div>
    );
  }

  // Placeholder — video not yet generated
  return (
    <div className="video-placeholder-box">
      <div className="video-placeholder-icon">🎬</div>
      <p className="video-placeholder-title">{title || "AI-Generated Video"}</p>
      <p className="video-placeholder-sub">Video will appear here once generated by AI</p>
    </div>
  );
}

export default VideoPlayer;
